export const RECEIVE_USER_CODE = 'RECEIVE_USER_CODE'

export const REQUEST_USER_DETAIL = 'REQUEST_USER_DETAIL'

export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL'

export const RECEIVE_USER_DETAIL = 'RECEIVE_USER_DETAIL'
