export const REQUEST_USER_CODE = 'REQUEST_USER_CODE'

export const RECEIVE_USER_CODE = 'RECEIVE_USER_CODE'

export const REQUEST_USER_DETAIL_BY_CODE = 'REQUEST_USER_DETAIL_BY_CODE'

export const FETCH_USER_DETAIL_BY_CODE = 'FETCH_USER_DETAIL_BY_CODE'

export const RECEIVE_USER_DETAIL_BY_CODE = 'RECEIVE_USER_DETAIL_BY_CODE'

export const REQUEST_USER_DETAIL_BY_ID = 'REQUEST_USER_DETAIL_BY_ID'

export const FETCH_USER_DETAIL_BY_ID = 'FETCH_USER_DETAIL_BY_ID'

export const RECEIVE_USER_DETAIL_BY_ID = 'RECEIVE_USER_DETAIL_BY_ID'
