export const SIGN_IN = 'SIGN_IN'

export const REQUEST_LOCATION = 'REQUEST_LOCATION'

export const FETCH_LOCATION = 'FETCH_LOCATION'

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION'

export const REQUEST_ADDRESS = 'REQUEST_ADDRESS'

export const FETCH_ADDRESS = 'FETCH_ADDRESS'

export const RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'

export const SHOW_ADDRESS = 'SHOW_ADDRESS'

export const UPDATE_CURRENTTIME = 'UPDATE_CURRENTTIME'

export const POST_SIGN_RECORD = 'POST_SIGN_RECORD'

export const POST_SIGN_RECORD_SUCCEED = 'POST_SIGN_RECORD_SUCCEED'

export const SIGN_BEFORE_FETCH_ADDRESS = 'SIGN_BEFORE_FETCH_ADDRESS'

export const END_SIGN_BEFORE_FETCH_ADDRESS = 'END_SIGN_BEFORE_FETCH_ADDRESS'

export const SAVE_WAIQIN_REMARK = 'SAVE_WAIQIN_REMARK'

export const REQUEST_WAIQIN_HISTORY = 'REQUEST_SIGN_HISTORY'

export const FETCH_WAIQIN_HISTORY = 'FETCH_SIGN_HISTORY'

export const RECEIVE_WAIQIN_HISTORY = 'RECEIVE_SIGN_HISTORY'
