export const SIGN_IN = 'SIGN_IN'

export const REQUEST_LOCATION = 'GET_LOCATION'

export const FETCH_LOCATION = 'FETCH_LOCATION'

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION'

export const REQUEST_ADDRESS = 'REQUEST_ADDRESS'

export const FETCH_ADDRESS = 'FETCH_ADDRESS'

export const RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'

export const SHOW_ADDRESS = 'SHOW_ADDRESS'
