export const SIGN_IN = 'SIGN_IN'

export const REQUEST_LOCATION = 'REQUEST_LOCATION'

export const FETCH_LOCATION = 'FETCH_LOCATION'

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION'

export const REQUEST_ADDRESS = 'REQUEST_ADDRESS'

export const FETCH_ADDRESS = 'FETCH_ADDRESS'

export const RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'

export const SHOW_ADDRESS = 'SHOW_ADDRESS'

export const UPDATE_CURRENTTIME = 'UPDATE_CURRENTTIME'

export const POST_SIGN_RECORD = 'POST_SIGN_RECORD'

export const POST_SIGN_RECORD_SUCCEED = 'POST_SIGN_RECORD_SUCCEED'

export const SIGN_BEFORE_FETCH_ADDRESS = 'SIGN_BEFORE_FETCH_ADDRESS'

export const END_SIGN_BEFORE_FETCH_ADDRESS = 'END_SIGN_BEFORE_FETCH_ADDRESS'

export const SAVE_WAIQIN_REMARK = 'SAVE_WAIQIN_REMARK'

export const CHANGE_WAIQIN_HISTORY_BY = 'CHANGE_WAIQIN_HISTORY_BY'

export const REQUEST_WAIQIN_HISTORY = 'REQUEST_SIGN_HISTORY'

export const FETCH_WAIQIN_HISTORY = 'FETCH_SIGN_HISTORY'

export const RECEIVE_WAIQIN_HISTORY = 'RECEIVE_SIGN_HISTORY'

export const CHANGE_WAIQIN_HISTORY_DATES = 'CHANGE_WAIQIN_HISTORY_DATES'

export const BEGIN_UPLOAD_WAIQIN_REMARK_IMAGE = 'BEGIN_UPLOAD_WAIQIN_REMARK_IMAGE'

export const SAVE_WAIQIN_REMARK_IMAGE = 'SAVE_WAIQIN_REMARK_IMAGE'

export const RECEIVE_WAIQIN_REMARK_IMAGE_URI = 'RECEIVE_WAIQIN_REMARK_IMAGE_URI'

export const REMOVE_WAIQIN_REMARK_IMAGE = 'REMOVE_WAIQIN_REMARK_IMAGE'

export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'

export const REMOVE_LOCATION = 'REMOVE_LOCATION'

export const REMOVE_LOCATION_AND_ADDRESS = 'REMOVE_LOCATION_AND_ADDRESS'
