export const WX_INITIAL = 'WX_INITIAL'

export const WX_INITIAL_SUCCEED = 'WX_INITIAL_SUCCEED'

export const REQUEST_WX_CONFIG = 'REQUEST_WX_CONFIG'

export const RECEIVE_WX_CONFIG = 'RECEIVE_WX_CONFIG'

export const RECEIVE_WX_CONFIG_FAILED = 'RECEIVE_WX_CONFIG_FAILED'
